FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5003

CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "5003"]