// <auto-generated />
using System;
using HTKISCloudOffice.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HTKISCloudOffice.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618014539_AlphaBDeviceAuth")]
    partial class AlphaBDeviceAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.AppAllowedRole", b =>
                {
                    b.Property<Guid>("app_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.HasKey("app_id", "role_id");

                    b.HasIndex("role_id");

                    b.ToTable("app_allowed_roles");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.AppFavorite", b =>
                {
                    b.Property<Guid>("favorite_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("app_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("favorite_id");

                    b.HasIndex("app_id");

                    b.HasIndex("user_id");

                    b.HasIndex("user_id", "app_id")
                        .IsUnique();

                    b.ToTable("app_favorites");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.AppIcon", b =>
                {
                    b.Property<Guid>("icon_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("icon_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("icon_type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("icon_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("uploaded_by")
                        .HasColumnType("uuid");

                    b.HasKey("icon_id");

                    b.HasIndex("icon_name");

                    b.ToTable("app_icons");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("app_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("app_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("icon_id")
                        .HasColumnType("uuid");

                    b.Property<string>("icon_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("launch_params")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("sort_order")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("app_id");

                    b.HasIndex("category");

                    b.HasIndex("is_active");

                    b.HasIndex("sort_order");

                    b.ToTable("applications");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("detail")
                        .HasColumnType("jsonb");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid>("resource_id")
                        .HasColumnType("uuid");

                    b.Property<string>("resource_type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("user_id1")
                        .HasColumnType("uuid");

                    b.HasKey("log_id");

                    b.HasIndex("action");

                    b.HasIndex("created_at");

                    b.HasIndex("user_id");

                    b.HasIndex("user_id1");

                    b.HasIndex("resource_type", "resource_id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.ConnectionAllowedRole", b =>
                {
                    b.Property<Guid>("connection_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.HasKey("connection_id", "role_id");

                    b.HasIndex("role_id");

                    b.ToTable("connection_allowed_roles");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.ConnectionConfig", b =>
                {
                    b.Property<Guid>("connection_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("connection_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("connection_params")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_remote_app")
                        .HasColumnType("boolean");

                    b.Property<string>("password_encrypted")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("port")
                        .HasColumnType("integer");

                    b.Property<string>("protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("remote_app_path")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("sort_order")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("connection_id");

                    b.HasIndex("is_active")
                        .HasDatabaseName("idx_conn_configs_is_active");

                    b.HasIndex("protocol")
                        .HasDatabaseName("idx_conn_configs_protocol");

                    b.HasIndex("sort_order")
                        .HasDatabaseName("idx_conn_configs_sort");

                    b.ToTable("connection_configs");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.DeviceBinding", b =>
                {
                    b.Property<Guid>("binding_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("device_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("device_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("device_token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("device_token_expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("last_login_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("last_login_ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("binding_id");

                    b.HasIndex("device_id")
                        .HasDatabaseName("idx_device_bindings_device_id");

                    b.HasIndex("device_token_expires_at")
                        .HasDatabaseName("idx_device_bindings_token_expires");

                    b.HasIndex("is_active")
                        .HasDatabaseName("idx_device_bindings_is_active");

                    b.HasIndex("user_id")
                        .HasDatabaseName("idx_device_bindings_user");

                    b.ToTable("device_bindings");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("token_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("token_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("token_id");

                    b.HasIndex("expires_at");

                    b.HasIndex("token_hash")
                        .IsUnique();

                    b.HasIndex("user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("permissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("role_id");

                    b.HasIndex("role_name")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.SharedDrive", b =>
                {
                    b.Property<Guid>("drive_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("allowed_permissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("drive_letter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("drive_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("drive_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("owner_id")
                        .HasColumnType("uuid");

                    b.Property<long>("quota_mb")
                        .HasColumnType("bigint");

                    b.Property<string>("samba_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("drive_id");

                    b.HasIndex("drive_letter");

                    b.HasIndex("drive_type");

                    b.ToTable("shared_drives");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("auto_login_token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("auto_login_token_expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("bound_vm_id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("user_id");

                    b.HasIndex("bound_vm_id");

                    b.HasIndex("department");

                    b.HasIndex("is_active");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("assigned_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("user_id", "role_id");

                    b.HasIndex("role_id");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.VmConfig", b =>
                {
                    b.Property<string>("vm_id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int>("max_users")
                        .HasColumnType("integer");

                    b.Property<string>("rdp_password_encrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("rdp_port")
                        .HasColumnType("integer");

                    b.Property<string>("rdp_username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("vm_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("vm_id");

                    b.HasIndex("is_active");

                    b.ToTable("vm_configs");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.AppAllowedRole", b =>
                {
                    b.HasOne("HTKISCloudOffice.Domain.Entities.Application", "Application")
                        .WithMany("app_allowed_roles")
                        .HasForeignKey("app_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HTKISCloudOffice.Domain.Entities.Role", "Role")
                        .WithMany("app_allowed_roles")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.AppFavorite", b =>
                {
                    b.HasOne("HTKISCloudOffice.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("app_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HTKISCloudOffice.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("HTKISCloudOffice.Domain.Entities.User", null)
                        .WithMany("audit_logs")
                        .HasForeignKey("user_id1");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.ConnectionAllowedRole", b =>
                {
                    b.HasOne("HTKISCloudOffice.Domain.Entities.ConnectionConfig", "ConnectionConfig")
                        .WithMany("connection_allowed_roles")
                        .HasForeignKey("connection_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HTKISCloudOffice.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectionConfig");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.DeviceBinding", b =>
                {
                    b.HasOne("HTKISCloudOffice.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("HTKISCloudOffice.Domain.Entities.User", "User")
                        .WithMany("refresh_tokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.User", b =>
                {
                    b.HasOne("HTKISCloudOffice.Domain.Entities.VmConfig", "BoundVm")
                        .WithMany()
                        .HasForeignKey("bound_vm_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BoundVm");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("HTKISCloudOffice.Domain.Entities.Role", "Role")
                        .WithMany("user_roles")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HTKISCloudOffice.Domain.Entities.User", "User")
                        .WithMany("user_roles")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.Application", b =>
                {
                    b.Navigation("app_allowed_roles");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.ConnectionConfig", b =>
                {
                    b.Navigation("connection_allowed_roles");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.Role", b =>
                {
                    b.Navigation("app_allowed_roles");

                    b.Navigation("user_roles");
                });

            modelBuilder.Entity("HTKISCloudOffice.Domain.Entities.User", b =>
                {
                    b.Navigation("audit_logs");

                    b.Navigation("refresh_tokens");

                    b.Navigation("user_roles");
                });
#pragma warning restore 612, 618
        }
    }
}
